# version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile_frontend
      args:
        - USER_UID=${UID}
        - USER_GID=${GID}
    user: "${UID}:${GID}"
    container_name: frontend
    volumes:
      - ./frontend:/frontend
    environment:
      USER_UID: ${UID}
      USER_GID: ${GID}
    ports:
      - "3000:3000"
    tty: true

    # volumes:
    #   - redis_data:/data