# version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile_frontend
      args:
        - USER_UID=${UID}
        - USER_GID=${GID}
    user: "${UID}:${GID}"
    container_name: niconico-vocaloid-frontend
    volumes:
      - ./frontend:/frontend
    environment:
      USER_UID: ${UID}
      USER_GID: ${GID}
    ports:
      - "3000:3000"
    tty: true

  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'testdb'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'
volumes:
  db-store: